- src/plugins/genshin/achieves/slip.ts
- src/plugins/genshin/init.ts
- src/plugins/genshin/module/slip.ts
- src/plugins/genshin/utils/api.ts
Add Fortune Slip to generate daily slip.
> feat: add Fortune Slip

- src/plugins/genshin/module/private/main.ts
- src/plugins/genshin/module/private/note.ts
- src/plugins/genshin/module/private/sign.ts
> feat: stop scheduled task when cancel the private service

- src/plugins/@management/ban.ts
> 解禁用户与群交换调整

- src/plugins/genshin/components/ledger/data-chart.js
> fix: chart font-family in ledger show incorrectly

- src/plugins/genshin/components/card/exploration-box.js
- src/plugins/genshin/public/js/card-data-parser.js
- src/plugins/genshin/routes/card-route.ts
- src/plugins/genshin/utils/api.ts
- src/plugins/genshin/utils/promise.ts
> fix: Explorations and homes in page uid show error

- package-lock.json
- package.json
- src/plugins/genshin/components/note/app.js
- src/plugins/genshin/components/note/info.js
> feat: Add parametric transformer display to uid page

- package-lock.json
- package.json
- src/plugins/genshin/achieves/uid-query.ts
- src/plugins/genshin/components/card/exploration-box.js
- src/plugins/genshin/components/character/app.js
- src/plugins/genshin/public/js/card-data-parser.js
> fix: page chara image rendering error

- package.json
- src/plugins/genshin/module/daily.ts
> fix: Incorrect display on page today before 4 o'clock

- package.json
- src/plugins/genshin/achieves/private/cancel.ts
- src/plugins/genshin/achieves/private/remove.ts
- src/plugins/genshin/module/private/main.ts
- src/plugins/genshin/setting.ts
> feat: Add remove specified user private service instruction

- package.json
- src/plugins/genshin/achieves/epitomized.ts
- src/plugins/genshin/setting.ts
> add weapon wish cancel select with order param 0

- package-lock.json
- package.json
- src/modules/bot.ts
- src/modules/config.ts
- src/plugins/genshin/achieves/guide.ts
- src/plugins/genshin/styles/info/character.css
- src/plugins/genshin/utils/api.ts
- 西风攻略图 404 提示
- 配置项：不允许非好友向 bot 私聊发送指令
> Add two feat

- package-lock.json
- package.json
- src/modules/bot.ts
- src/plugins/genshin/init.ts
> two bug fix

- .gitignore
- Dockerfile
- adachi-bot.config.js
- package-lock.json
- package.json
- src/plugins/@management/init.ts
- src/plugins/@management/upgrade.ts
- use pm2 to instead forever
- add upgrade command to update application
**注：** docker 启动时若想要使用upgrade指令需要将package.json文件取消挂载。
> use pm2 to instead forever

- .gitignore
- Dockerfile
- adachi-bot.config.js
- docker-compose.yml
- package-lock.json
- package.json
- src/plugins/@management/init.ts
- src/plugins/@management/upgrade.ts
- use pm2 to instead forever and add upgrade cmdKey
- fix win start error(add "win-start" script)
- optimize dockerfile
- not support win to use "upgrade" cmdKey
> use pm2 to instead forever and add upgrade cmdKey

- .gitignore
- Dockerfile
- adachi-bot.config.js
- docker-compose.yml
- package-lock.json
- package.json
- src/modules/bot.ts
- src/plugins/@management/init.ts
- src/plugins/@management/upgrade.ts
- src/plugins/genshin/achieves/private/query/abyss.ts
- src/plugins/genshin/components/abyss-single/app.js
- src/plugins/genshin/components/abyss-single/floor.js
- src/plugins/genshin/components/abyss-single/overview.js
- src/plugins/genshin/components/abyss-single/reveal.js
- src/plugins/genshin/components/abyss-single/room.js
- src/plugins/genshin/components/abyss/overview.js
- src/plugins/genshin/public/js/abyss-data-parser.js
- src/plugins/genshin/routes/abyss-route.ts
- src/plugins/genshin/setting.ts
- src/plugins/genshin/styles/abyss-single/app.css
- src/plugins/genshin/styles/abyss-single/floor.css
- src/plugins/genshin/styles/abyss-single/overview.css
- src/plugins/genshin/styles/abyss-single/reveal.css
- src/plugins/genshin/styles/abyss-single/room.css
- src/plugins/genshin/utils/promise.ts
- src/plugins/genshin/views/abyss-single.html
- 项目更改为 pm2 启动
- 深渊新增一图流显示，原多图转发改为参数 -l
- 添加 upgrade 热更新指令并优化
- bot 启动后发送提示消息
> update to ver2.3.1

- Dockerfile
- package-lock.json
- package.json
- src/modules/bot.ts
- 添加登录交互方式，不必在登录有设备锁等验证时让终端交互成为必需品。
- 优化`Dockerfile`，避免每次容器启动都下载一次浏览器。
> change IXD of login and optimize Dockerfile

- package-lock.json
- package.json
- redis.conf
- src/modules/bot.ts
- src/modules/config.ts
- src/modules/database.ts
- src/modules/message.ts
- 支持使用密码连接`redis`(默认还是用无密码，仅给有需求的提供配置)
- 优化`atUser`选项，在消息与`@`之间加一个空格
> support db password connection and optimize atUser

- package-lock.json
- package.json
- src/modules/renderer.ts
- 添加自定义渲染的方式
- 添加`viewPort`参数设置浏览器的设备信息
> add render from callback function

- package-lock.json
- package.json
- src/plugins/genshin/achieves/wish.ts
- src/plugins/genshin/module/config.ts
> feature: support config genshin.yml to limit wish numbers.

- package-lock.json
- package.json
- src/plugins/genshin/achieves/wish.ts
> fixed: wish until can't use bug.

- package-lock.json
- package.json
- src/plugins/@management/init.ts
- src/plugins/@management/restart.ts
- src/plugins/genshin/components/info/base.js
- src/plugins/genshin/styles/info/base.css
- src/plugins/genshin/styles/info/info-card.css
- src/plugins/genshin/styles/info/info-line.css
> update to ver2.3.9

- package-lock.json
- package.json
- src/plugins/genshin/achieves/wish.ts
- src/plugins/genshin/styles/info-artifact/app.css
- the until cannot be used when wishLimitNum is less than 99
- some text is covered on page artifact info
> fix two bugs:

- src/web-console/api/request.js
- src/web-console/assets/styles/view/login.css
- src/web-console/permission.js
- src/web-console/store/modules/user.js
- src/web-console/utils/session.js
- src/web-console/utils/validate.js
- src/web-console/views/login.js
控制台相关
- 新增登录记住账号
- 用户列表新增订阅展示筛选及管理
> update to ver2.4.1

- src/plugins/genshin/utils/net-utils.ts
添加一个获取可用端口的工具类，可以避免因为端口占用导致用户需要自行频繁修改端口。
> add net-utils to find a usable port.

- package.json
- src/modules/bot.ts
- src/modules/chat.ts
> feat：默认调用青云客api回复私聊消息和群@BOT消息（非指令）

- package.json
- src/modules/bot.ts
- src/modules/chat.ts
- src/plugins/genshin/module/cookies.ts
- src/plugins/genshin/utils/promise.ts
fix: 对自动回复做出一点优化，尽量不使用messageData本身试试还会BUG否
> fix：优化cookie使用次数耗尽切换流程

- adachi-bot.config.js
- package-lock.json
- package.json
- src/plugins/@management/restart.ts
- src/plugins/@management/upgrade.ts
支持 `windows` 系统使用 `pm2` 的方式启动项目，以及使用 `#restart` 和 `#upgrade` 指令。
> feature: winos support to use pm2 start and use restart、upgrade command.

- adachi-bot.config.js
- package-lock.json
- package.json
- src/modules/logger.ts
修复 `Linux` 中使用 `cluster` 模式会导致 `webConsole` 无法使用的问题。
> fixed: fix linux use cluster mode to make webConsole unusable.

- package-lock.json
- package.json
- src/plugins/genshin/achieves/today.ts
- src/plugins/genshin/components/daily/app.js
- src/plugins/genshin/components/daily/event.js
- src/plugins/genshin/components/daily/header.js
- src/plugins/genshin/module/daily.ts
- src/plugins/genshin/setting.ts
- src/plugins/genshin/styles/daily/event.css
- src/plugins/genshin/styles/daily/header.css
> feat: Command #today add specific date material query

- package-lock.json
- package.json
- src/modules/bot.ts
- src/modules/config.ts
- src/plugins/@help/achieves/call.ts
- src/plugins/@help/achieves/help.ts
- src/plugins/@help/init.ts
- src/plugins/@help/view/app.js
- src/plugins/genshin/achieves/almanac.ts
- src/plugins/genshin/achieves/artifact.ts
- src/plugins/genshin/achieves/info.ts
- src/plugins/genshin/achieves/private/query/abyss.ts
- src/plugins/genshin/achieves/private/query/character.ts
- src/plugins/genshin/achieves/private/query/mys.ts
- src/plugins/genshin/achieves/private/replace.ts
- src/plugins/genshin/achieves/private/subscribe.ts
- src/plugins/genshin/achieves/uid-query.ts
- src/plugins/genshin/achieves/wish.ts
- src/plugins/genshin/module/daily.ts
- src/plugins/genshin/module/private/main.ts
- src/plugins/genshin/module/private/note.ts
- src/plugins/genshin/module/private/sign.ts
- src/plugins/genshin/utils/private.ts
- src/plugins/genshin/utils/promise.ts
> update to ver2.4.7

- package.json
- src/modules/bot.ts
- src/modules/chat.ts
- src/modules/config.ts
fix: 修复atBOT=false时，自动回复未去掉CQ头消息问题
> feat: 新增腾讯NLP平台聊天接口，并提供配置项

- package-lock.json
- package.json
- src/plugins/genshin/components/daily/event.js
> fix: Event progress bar length display incorrectly

- .dockerignore
- Dockerfile
- docker-compose.yml
- package-lock.json
- package.json
- Docker 镜像优化为 alpine 系统，大幅度缩减镜像大小
- 升级 redis 镜像版本，修复 redis 的 CVE 漏洞
- 文件挂载、镜像 tag 等优化
- 增加系统中文字体，使用文泉译微软雅黑字体
> feature: improved docker image and upgrade redis to fix some CVE

- package-lock.json
- package.json
- src/modules/message.ts
> Optimize the style of reply messages when enable the atUser config.

- package.json
- src/modules/bot.ts
> fix @BOT false时候 模式识别未去掉@信息

- package-lock.json
- package.json
- src/plugins/genshin/achieves/private/note/now.ts
- src/plugins/genshin/module/private/note.ts
> fix: Modify the error message of the #note when cookie is invalid

- package-lock.json
- package.json
- src/modules/bot.ts
- src/modules/config.ts
- src/modules/utils.ts
- src/plugins/@help/init.ts
- src/plugins/@help/server.ts
- src/plugins/@help/utils/filter.ts
- src/plugins/genshin/init.ts
- src/plugins/genshin/server.ts
- 移动原本的 `net-utils.ts` 并重命名为 `utils.ts`
- 如果用户未填写 `webconsole` 的 `jwtSecret`，则为其随机生成一个 `secret`
- 在端口冲突情况生成 `genshin`、`@help` 的 server port
- 优化 `Docker` 模式下登录 `ticket` 的获取
> improve some code and add some feature

- package-lock.json
- package.json
- src/modules/bot.ts
- src/plugins/@management/upgrade-plugins.ts
- src/plugins/genshin/utils/api.ts
- 修复米游社签到 `invalid request` bug
- 优化更新插件指令出错或者已是最新时的消息，合并发送这些消息
> fix signin bug and improve upgrade plugin error message

- package-lock.json
- package.json
- src/modules/command/order.ts
- src/plugins/genshin/components/note/app.js
- src/plugins/genshin/module/private/note.ts
- src/plugins/genshin/setting.ts
- src/plugins/genshin/types/note.ts
- src/plugins/genshin/types/sign-in.ts
- src/plugins/genshin/utils/promise.ts
- src/web-console/assets/styles/common.css
- src/web-console/assets/styles/layout/system.css
- src/web-console/backend/routes/group.ts
- src/web-console/layout/system/tabs.js
- src/web-console/router/system.js
- src/web-console/views/message/index.js
- src/web-console/views/user/group/group-detail.js
- src/web-console/views/user/group/index.js
- src/web-console/views/user/group/send-msg.js
- src/web-console/views/user/user/index.js
- src/web-console/views/user/user/user-detail.js
- 部分指令携带空格匹配失败
- #uid 无法校验参数格式，参数错误时渲染图片错误
- 参量质变仪修正名称， 修复提示时间不准确、提示两次问题
- 签到遭遇验证码时给予提示
> update to ver2.6.7

- package-lock.json
- package.json
- src/modules/database.ts
- src/modules/renderer.ts
- src/plugins/genshin/public/js/card-data-parser.js
- src/plugins/genshin/types/user-info.ts
- src/plugins/genshin/utils/promise.ts
- src/web-console/assets/styles/view/log.css
- src/web-console/assets/styles/view/user.css
- src/web-console/backend/routes/group.ts
- src/web-console/backend/routes/log.ts
- src/web-console/views/log.js
- src/web-console/views/user/group/group-detail.js
- src/web-console/views/user/group/send-msg.js
- ck过期深渊查询不显示错误提示问题
- uid 和 mys 新增草神瞳展示
- 修改控制台群发消息延时策略
- 控制台日志新增日志等级与消息类型筛选
> update to ver2.6.8

- package-lock.json
- package.json
- src/modules/bot.ts
处理设备锁事件时链接中无二维码的问题，使用绑定的手机号验证。
> fix device lock event bug.

- package-lock.json
- package.json
- src/web-console/api/api.js
- src/web-console/assets/styles/components.css
- src/web-console/backend/routes/config.ts
- src/web-console/components/spread-form-item/index.js
- src/web-console/router/system.js
- src/web-console/utils/validate.js
- src/web-console/views/dashboard/commands.js
- src/web-console/views/dashboard/cookies.js
- src/web-console/views/dashboard/plugins.js
- src/web-console/views/dashboard/setting.js
- 修复控制台部分配置项修改未生效问题
- 优化控制台配置页，同时只允许展开一个展开项
- 控制台新增插件配置文件修改页
> update to v2.7.2

- Dockerfile
- package-lock.json
- package.json
> Remove Dockerfile conflict info

- package-lock.json
- package.json
- src/web-console/assets/styles/index.css
- src/web-console/main.js
> fix: Some devices open the webconsole white screen

- package-lock.json
- package.json
- src/modules/bot.ts
- src/modules/config.ts
- src/plugins/genshin/module/private/note.ts
> update to ver2.7.8

- package-lock.json
- package.json
- src/modules/bot.ts
- src/web-console/views/dashboard/setting.js
> Partial adjustment for v2.7.8

- package-lock.json
- package.json
- src/modules/bot.ts
- src/modules/config.ts
- src/modules/management/interval.ts
- src/web-console/backend/routes/group.ts
- src/web-console/backend/routes/user.ts
- src/web-console/views/dashboard/setting.js
新增配置项 ThresholdInterval，指令使用超出阈值后当前小时内限制其使用
> feat: New configuration item ThresholdInterval

- src/plugins/genshin/types/verify-code.ts
> 修复genshin初始化失败问题

- src/plugins/genshin/utils/api.ts
> fix：mys sign verify code update

- Dockerfile
- package-lock.json
- package.json
- src/web-console/assets/styles/view/message.css
- src/web-console/backend/routes/group.ts
- src/web-console/backend/routes/user.ts
- src/web-console/utils/url.js
- src/web-console/views/log.js
- src/web-console/views/message/send-message.js
- 修复控制台日志和用户模块显示空数据问题
- 修改控制台消息处理弹窗图片预览方式，解决防盗链
- 修复 docker 构建报错问题
> update to 2.9.1(verify)

- src/web-console/views/login.js
> feat:Get the year dynamically (Login Page)

- package-lock.json
- package.json
- src/modules/bot.ts
- src/modules/chat.ts
- src/modules/config.ts
- src/modules/mail.ts
- src/modules/utils.ts
- src/web-console/views/dashboard/setting.js
- 自动聊天新增小爱同学，支持发送语音
- 新增 ffmpegPath 与 ffprobePath 配置项（发送语音、视频必须）
- 新增邮件模块，使用方式与 message 模块类似
- 支持 bot 离线一段时间后向主人发送邮件提醒
> update to ver2.9.2 (Verify)

- package-lock.json
- package.json
- src/web-console/backend/routes/config.ts
> fix: Modify plugin config item exception

- Dockerfile
- docker-entrypoint.sh
- src/modules/renderer.ts
- 优化`Dockerfile`，容器内添加自定义用户`adachi`，降低容器内用户的权限，同时解决挂载时宿主机权限低于或高于容器权限的问题。
- 优化截图类型为`jpeg`降低截图大小，避免图片太大导致上传失败。
> improved: 优化Dockerfile

- adachi-bot.service
给pm2出现各种奇怪问题的用户以systemd解决方案
其中WorkingDirectory按照自己的情况修改
> The systemd solution

- src/modules/lib/client.ts
- src/modules/lib/types/api/params.ts
- src/modules/lib/types/map/api.ts
- src/modules/management/assets.ts
- src/modules/renderer.ts
- src/plugins/@management/upgrade-plugins.ts
- src/plugins/@management/upgrade.ts
- opt: optimize code
- feat: add the feature of install dependencies
> one feature and some optimize.

- .editorconfig
- .github/workflows/docker-image.yml
- Dockerfile.base
- docker-entrypoint.sh
- package.json
- pnpm-lock.yaml
- src/modules/lib/core/base-client/default.ts
- src/plugins/@management/upgrade-plugins.ts
- src/plugins/@management/upgrade.ts
- src/utils/async.ts
- src/utils/system.ts
- src/utils/url.ts
- fix: 修复指令更新时依赖无法安装成功
- fix: 修复ws server不支持 443 端口
- fix: 修复 docker 容器启动可能出现的权限等问题
- feat: 容器内增加 emoji 字体
- feat: 增加工作流构建项目基础镜像
- style: 修改 markdown 中 yaml 代码块的格式化方式
- chore: 优化依赖让仅安装生产环境依赖可正常运行
> 修复一些BUG以及增加Action构建基础镜像的功能
